### ISSUE TITLE
cpe_firefox uses internal variables

### ISSUE THREAD

**Issue by natewalck** [facebook/IT-CPE#74]
Looks like cpe_firefox is not completely decoupled:

```
================================================================================
Recipe Compile Error in /Users/nate/.chef/local-mode-cache/cache/cookbooks/cpe_init/recipes/default.rb
================================================================================

NameError
---------
uninitialized constant #<Class:#<Chef::Recipe:0x007fbe3ac06340>>::CPE

Cookbook Trace:
---------------
  /Users/nate/.chef/local-mode-cache/cache/cookbooks/cpe_firefox/recipes/mac_os_x_firefox.rb:62:in `block in from_file'
  /Users/nate/.chef/local-mode-cache/cache/cookbooks/cpe_firefox/recipes/mac_os_x_firefox.rb:22:in `each'
  /Users/nate/.chef/local-mode-cache/cache/cookbooks/cpe_firefox/recipes/mac_os_x_firefox.rb:22:in `from_file'
  /Users/nate/.chef/local-mode-cache/cache/cookbooks/cpe_firefox/recipes/default.rb:16:in `from_file'
  /Users/nate/.chef/local-mode-cache/cache/cookbooks/cpe_init/recipes/mac_os_x_init.rb:58:in `block in from_file'
  /Users/nate/.chef/local-mode-cache/cache/cookbooks/cpe_init/recipes/mac_os_x_init.rb:57:in `each'
  /Users/nate/.chef/local-mode-cache/cache/cookbooks/cpe_init/recipes/mac_os_x_init.rb:57:in `from_file'
  /Users/nate/.chef/local-mode-cache/cache/cookbooks/cpe_init/recipes/default.rb:17:in `from_file'

Relevant File Content:
----------------------
/Users/nate/.chef/local-mode-cache/cache/cookbooks/cpe_firefox/recipes/mac_os_x_firefox.rb:

 55:    local_settings_file = resources_dir + local_settings
 56:    file local_settings_file.to_s do
 57:      action :delete
 58:    end
 59:
 60:    # We're going to place the configs in /Library/CPE/browsers/firefox/
 61:    ff_central_store =
 62>>     Pathname.new(CPE.get_cpe_path('cpe')) + 'browsers' + 'firefox'
 63:    remote_directory ff_central_store.to_s do
 64:      source 'firefox'
 65:      owner 'root'
 66:      group 'wheel'
 67:      mode '0775'
 68:      recursive true
 69:    end
 70:
 71:    # Apply the new config template

Platform:
---------
x86_64-darwin13
```

**Comment by mikedodge04** [comment]
https://github.com/facebook/IT-CPE/blob/master/chef/cookbooks/cpe_firefox/recipes/darwin_firefox.rb
